# Generated by Django 4.0.4 on 2023-02-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_message_message_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
